### ISSUE TITLE
Needed time for search_accu.py

### ISSUE THREAD

**Issue by PJChoi1** [UoS-EEC/DynamicOFA#2]
![image](https://user-images.githubusercontent.com/86999406/221405533-e250030b-2ce7-4318-adfa-bbfc7b0b7940.png)

Hello, I'm currently running search_accu.py with i9-10900K and RTX3080. 
It's been 2 days since I started running and it is still running. 
How long does search_accu.py take to finish?

**Comment by Lewislou** [comment]
Hi, from the logs that you provided. Seems that the current latency constraint range is not valid. So the code is actually waiting for you to input a valid constraint range and has not started yet. You need to change the latency constraint range at Line 56 in "evolution_finder_accu.py". For example, if your want to search for the sub-networks in the latency range [820,1000], you can set the constraint range at Line 56 as [0,1200]. Then the codes are good to go.

A hint: The latency table is built on Jetson CPU. So within the latency range [820,1000], the sub-networks are supposed to be small ones, if you want to do a fast search, you can shrink the search space at Lines 12-15 in "evolution_finder_accu.py" by only choosing the small kernel size, depth, input size and so on. But if time is not an issue, you can just use the large search space like the current setting in "evolution_finder_accu.py". Hope this answer helps you~

**Comment by PJChoi1** [comment]
Thanks for your kind response. I've successfully finished all the tests. I really appreciate it.
